# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f480a64cd59854a1e9b4001deb6ca966ea675600921d45b44da03d4ac9715eddb4ec7d2233b9c5217bb6f92224ffe94ddc3bd35b1d885a23048c12259e394c

test:
  secret_key_base: 4077018d82a3570f8703da66438b0e9d9164811f02916be964a3fd0d3f8a0148cf14c186455ad3e42a7a2d02d782a49d29bd78d944882ddee53b7f0fb088444e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
